@extends('user.Profile.master')
@section('header')
    @yield('header')
@endsection
@section('content')
    @yield('content')
@endsection
@section('content2')
    @yield('content2')
@endsection
@section('main')
    @yield('main')
@endsection